name: 🐛 Report a Problem
description: Something isn't working as expected? Let us know!
title: "[Problem]: "
labels: ["bug", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        ## Thanks for helping improve renaym! 🎬
        
        Please fill out the form below to help us understand and fix the issue.
        Don't worry about being too technical - just describe what happened!

  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Describe what went wrong in your own words.
      placeholder: "Example: When I tried to rename my movie files, the app showed an error message and nothing happened."
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: What did you expect to happen?
      description: What were you hoping would happen instead?
      placeholder: "Example: I expected my files to be renamed with the correct movie titles from TMDB."
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      description: What did you do right before the problem occurred? This helps us recreate the issue.
      placeholder: |
        1. I opened renaym
        2. I dragged my movie folder into the app
        3. I clicked the "Rename" button
        4. The error appeared
    validations:
      required: true

  - type: dropdown
    id: media-type
    attributes:
      label: What type of files were you working with?
      options:
        - Movies
        - TV Shows
        - Both
        - Not applicable
    validations:
      required: true

  - type: dropdown
    id: os
    attributes:
      label: What operating system are you using?
      options:
        - Windows
        - macOS (Intel)
        - macOS (Apple Silicon / M1/M2/M3)
        - Linux
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: renaym version
      description: You can find this in the app (Help → About) or from the download filename.
      placeholder: "Example: 1.0.0"
    validations:
      required: false

  - type: textarea
    id: error-message
    attributes:
      label: Error message (if any)
      description: If you saw an error message, please copy and paste it here. Screenshots are also helpful!
      placeholder: "Paste any error message you saw, or describe what the error looked like."
    validations:
      required: false

  - type: textarea
    id: additional
    attributes:
      label: Anything else?
      description: Any other details that might help us? Screenshots, example filenames (without personal info), etc.
      placeholder: "Add any other information that might be helpful..."
    validations:
      required: false

  - type: checkboxes
    id: checklist
    attributes:
      label: Before submitting
      options:
        - label: I've checked that the AI model finished downloading (first-time setup)
          required: false
        - label: I've checked that my TMDB API key is configured correctly
          required: false

